package com.pricofy.pricofy_front_flutter

import android.content.Context
import com.google.android.play.core.integrity.IntegrityManagerFactory
import com.google.android.play.core.integrity.IntegrityTokenRequest
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import java.security.MessageDigest

/**
 * PlatformAttestationHandler
 *
 * Handles platform attestation for Android using Play Integrity API.
 * This validates that requests come from legitimate, unmodified devices
 * running an app installed from Google Play Store.
 *
 * Play Integrity provides:
 * - App integrity (app is unmodified and from Play Store)
 * - Device integrity (device passes Google's security checks)
 * - License status (app is legitimately purchased/installed)
 *
 * Note: Play Integrity requires the app to be registered in Google Play Console.
 * For development/testing, mock tokens are generated by the Flutter service.
 */
class PlatformAttestationHandler : FlutterPlugin, MethodChannel.MethodCallHandler {
    private lateinit var channel: MethodChannel
    private lateinit var context: Context

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        context = binding.applicationContext
        channel = MethodChannel(binding.binaryMessenger, "com.pricofy/platform_attestation")
        channel.setMethodCallHandler(this)
    }

    override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
        when (call.method) {
            "getPlayIntegrityToken" -> {
                val nonce = call.argument<String>("nonce")
                val response = call.argument<String>("response")

                if (nonce == null || response == null) {
                    result.error(
                        "INVALID_ARGS",
                        "Missing nonce or response arguments",
                        null
                    )
                    return
                }

                getIntegrityToken(nonce, response, result)
            }
            else -> result.notImplemented()
        }
    }

    /**
     * Request a Play Integrity token
     *
     * The token is bound to:
     * - The specific device
     * - The app package name and signing certificate
     * - A nonce (challenge) for replay protection
     *
     * @param nonce Server challenge nonce
     * @param response PoW response (for binding)
     * @param result Flutter method result callback
     */
    private fun getIntegrityToken(nonce: String, response: String, result: MethodChannel.Result) {
        // Create a unique challenge by combining nonce and response
        val challenge = "$nonce:$response"
        val challengeHash = sha256Base64(challenge)

        println("[PlatformAttest] Generating Play Integrity token for nonce: ${nonce.take(16)}...")

        try {
            val integrityManager = IntegrityManagerFactory.create(context)

            // Build the integrity token request
            // Note: setCloudProjectNumber is optional but recommended for server-side validation
            val tokenRequest = IntegrityTokenRequest.builder()
                .setNonce(challengeHash)
                .build()

            integrityManager
                .requestIntegrityToken(tokenRequest)
                .addOnSuccessListener { response ->
                    val token = response.token()

                    // Return with prefix for easy parsing on backend
                    val formattedToken = "android_integrity:$token"

                    println("[PlatformAttest] Play Integrity token generated successfully (length: ${token.length})")
                    result.success(formattedToken)
                }
                .addOnFailureListener { exception ->
                    println("[PlatformAttest] Play Integrity error: ${exception.message}")

                    // Map common errors to user-friendly messages
                    val errorCode: String
                    val errorMessage: String

                    when {
                        exception.message?.contains("API_NOT_AVAILABLE") == true -> {
                            errorCode = "API_NOT_AVAILABLE"
                            errorMessage = "Play Integrity API not available. Ensure Google Play Services is installed and updated."
                        }
                        exception.message?.contains("PLAY_STORE_NOT_FOUND") == true -> {
                            errorCode = "PLAY_STORE_NOT_FOUND"
                            errorMessage = "Google Play Store not found. This device may not support Play Integrity."
                        }
                        exception.message?.contains("NETWORK_ERROR") == true -> {
                            errorCode = "NETWORK_ERROR"
                            errorMessage = "Network error while contacting Play Integrity servers."
                        }
                        exception.message?.contains("APP_NOT_INSTALLED") == true -> {
                            errorCode = "APP_NOT_INSTALLED"
                            errorMessage = "App not installed from Play Store. Sideloaded apps cannot use Play Integrity."
                        }
                        exception.message?.contains("TOO_MANY_REQUESTS") == true -> {
                            errorCode = "RATE_LIMITED"
                            errorMessage = "Too many integrity requests. Please try again later."
                        }
                        else -> {
                            errorCode = "PLAY_INTEGRITY_ERROR"
                            errorMessage = exception.message ?: "Unknown Play Integrity error"
                        }
                    }

                    result.error(errorCode, errorMessage, exception.stackTraceToString())
                }
        } catch (e: Exception) {
            println("[PlatformAttest] Exception creating IntegrityManager: ${e.message}")
            result.error(
                "INTEGRITY_INIT_ERROR",
                "Failed to initialize Play Integrity: ${e.message}",
                e.stackTraceToString()
            )
        }
    }

    /**
     * Generate SHA-256 hash of input and encode as base64url
     * This is used to create the nonce for Play Integrity
     */
    private fun sha256Base64(input: String): String {
        val digest = MessageDigest.getInstance("SHA-256")
        val hash = digest.digest(input.toByteArray(Charsets.UTF_8))

        // Encode as base64url (URL-safe base64 without padding)
        return android.util.Base64.encodeToString(
            hash,
            android.util.Base64.URL_SAFE or android.util.Base64.NO_WRAP or android.util.Base64.NO_PADDING
        )
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        channel.setMethodCallHandler(null)
    }
}
