// Mocks generated by Mockito 5.4.6 from annotations
// in pricofy_front_flutter/test/product_form_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pricofy_front_flutter/core/api/bff_api_client.dart' as _i3;
import 'package:pricofy_front_flutter/core/models/request.dart' as _i6;
import 'package:pricofy_front_flutter/core/models/user.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BffApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockBffApiClient extends _i1.Mock implements _i3.BffApiClient {
  MockBffApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<Map<String, dynamic>> submitSearch({
    required String? searchText,
    String? searchType = 'normal',
    List<String>? sources = const [],
    String? userLanguage,
    String? country,
    Map<String, double>? gps,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitSearch,
          [],
          {
            #searchText: searchText,
            #searchType: searchType,
            #sources: sources,
            #userLanguage: userLanguage,
            #country: country,
            #gps: gps,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> submitEvaluationWithPhotos(
    Map<String, dynamic>? formData,
    List<dynamic>? photos,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitEvaluationWithPhotos,
          [
            formData,
            photos,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getResults(
    String? searchId, {
    List<String>? scrapers,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getResults,
          [searchId],
          {
            #scrapers: scrapers,
            #cancelToken: cancelToken,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getStatus(
    String? searchId, {
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatus,
          [searchId],
          {#cancelToken: cancelToken},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getSearchHistory({
    int? limit = 20,
    String? cursor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchHistory,
          [],
          {
            #limit: limit,
            #cursor: cursor,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.User> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
      ) as _i4.Future<_i2.User>);

  @override
  _i4.Future<_i2.User> updateUserProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [data],
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #updateUserProfile,
            [data],
          ),
        )),
      ) as _i4.Future<_i2.User>);

  @override
  _i4.Future<List<dynamic>> getUserEvaluations() => (super.noSuchMethod(
        Invocation.method(
          #getUserEvaluations,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> submitContact({
    required String? nombre,
    required String? email,
    required String? telefono,
    required String? comentario,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitContact,
          [],
          {
            #nombre: nombre,
            #email: email,
            #telefono: telefono,
            #comentario: comentario,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> detectCountry() => (super.noSuchMethod(
        Invocation.method(
          #detectCountry,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> detectLocation({
    double? lat,
    double? lon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #detectLocation,
          [],
          {
            #lat: lat,
            #lon: lon,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> clearSession() => (super.noSuchMethod(
        Invocation.method(
          #clearSession,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.User> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i4.Future<_i2.User>);

  @override
  _i4.Future<_i2.User> updateProfile({
    String? firstName,
    String? lastName,
    String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #phone: phone,
          },
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #firstName: firstName,
              #lastName: lastName,
              #phone: phone,
            },
          ),
        )),
      ) as _i4.Future<_i2.User>);

  @override
  _i4.Future<List<_i6.Request>> getMyEvaluations() => (super.noSuchMethod(
        Invocation.method(
          #getMyEvaluations,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Request>>.value(<_i6.Request>[]),
      ) as _i4.Future<List<_i6.Request>>);

  @override
  _i4.Future<Map<String, dynamic>> getEvaluationDetail(String? evaluationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvaluationDetail,
          [evaluationId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> initLogin(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #initLogin,
          [email],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> sendCode(
    String? email, {
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendCode,
          [email],
          {#language: language},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> verifyCode(
    String? email,
    String? code,
    String? session,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyCode,
          [
            email,
            code,
            session,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<dynamic>> getAllSolicitudes() => (super.noSuchMethod(
        Invocation.method(
          #getAllSolicitudes,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<List<dynamic>> getAllContactos() => (super.noSuchMethod(
        Invocation.method(
          #getAllContactos,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<List<dynamic>> getAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> deleteUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateAdminUserProfile(
    String? userId, {
    String? firstName,
    String? lastName,
    String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAdminUserProfile,
          [userId],
          {
            #firstName: firstName,
            #lastName: lastName,
            #phone: phone,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateUserGroup(
    String? userId, {
    required String? group,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserGroup,
          [userId],
          {#group: group},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> get(
    String? endpoint, {
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #queryParameters: queryParameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> post(
    String? endpoint, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #data: data,
            #queryParameters: queryParameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
