import { Category, Product, Listing, Conversation, Message, Order, Alert } from "@/types";

// ==========================================
// CATEGORIES
// ==========================================

export const mockCategories: Category[] = [
  // === ELECTRÓNICA DE CONSUMO ===
  {
    id: "cat-smartphones",
    name: "Smartphones",
    slug: "smartphones",
    icon: "📱",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-tablets",
    name: "Tablets",
    slug: "tablets",
    icon: "📲",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-laptops",
    name: "Portátiles",
    slug: "laptops",
    icon: "💻",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-desktops",
    name: "Ordenadores de sobremesa",
    slug: "desktops",
    icon: "🖥️",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-monitors",
    name: "Monitores",
    slug: "monitors",
    icon: "🖥️",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-consoles",
    name: "Consolas",
    slug: "consoles",
    icon: "🎮",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-audio",
    name: "Audio",
    slug: "audio",
    icon: "🎧",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-wearables",
    name: "Wearables",
    slug: "wearables",
    icon: "⌚",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-cameras",
    name: "Cámaras y Fotografía",
    slug: "cameras",
    icon: "📷",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-tv",
    name: "Televisores",
    slug: "tv",
    icon: "📺",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-projectors",
    name: "Proyectores",
    slug: "projectors",
    icon: "📽️",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  // === ELECTRODOMÉSTICOS ===
  {
    id: "cat-appliances-large",
    name: "Grandes Electrodomésticos",
    slug: "appliances-large",
    icon: "🧊",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-appliances-small",
    name: "Pequeños Electrodomésticos",
    slug: "appliances-small",
    icon: "🍳",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-climate",
    name: "Climatización",
    slug: "climate",
    icon: "❄️",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  // === MOVILIDAD ===
  {
    id: "cat-ebikes",
    name: "Bicicletas Eléctricas",
    slug: "ebikes",
    icon: "🚲",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-scooters",
    name: "Patinetes Eléctricos",
    slug: "scooters",
    icon: "🛴",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  // === OTROS ===
  {
    id: "cat-drones",
    name: "Drones",
    slug: "drones",
    icon: "🚁",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-gaming",
    name: "Accesorios Gaming",
    slug: "gaming",
    icon: "🕹️",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-networking",
    name: "Redes y Conectividad",
    slug: "networking",
    icon: "📡",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-storage",
    name: "Almacenamiento",
    slug: "storage",
    icon: "💾",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-peripherals",
    name: "Periféricos",
    slug: "peripherals",
    icon: "⌨️",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-other",
    name: "Otros",
    slug: "other",
    icon: "📦",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
];

// ==========================================
// PRODUCTS (Wallet)
// ==========================================

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    userId: "user-1",
    categoryId: "cat-smartphones",
    category: mockCategories[0],
    brand: "Apple",
    model: "iPhone 15 Pro",
    variant: "256GB Titanio Natural",
    condition: "LIKE_NEW",
    purchaseDate: new Date("2024-09-20"),
    purchasePrice: 1329,
    purchaseStore: "Apple Store",
    proofOfPurchaseUrl: "/mock/ticket-iphone.jpg",
    warrantyEndDate: new Date("2026-09-20"),
    imeiLast4: "7842",
    photos: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800",
      "https://images.unsplash.com/photo-1696426051872-0ecc5cc0fba4?w=800",
    ],
    accessories: { "Cable USB-C": true, "Caja original": true, "Cargador": false, "SIM tool": true },
    estimatedValue: 1050,
    estimatedValueUpdatedAt: new Date(),
    // === INFORMACIÓN ENRIQUECIDA POR IA ===
    resaleValue: {
      percentage: 79,
      minPrice: 980,
      maxPrice: 1120,
      marketTrend: "stable",
      notes: "Alta demanda, modelo reciente. Mantiene muy bien el valor.",
    },
    manualUrl: "https://support.apple.com/es-es/guide/iphone/welcome/ios",
    warrantyContact: {
      phone: "900 150 503",
      email: undefined,
      url: "https://support.apple.com/es-es/repair",
      hours: "L-V 9:00-21:00, S 9:00-18:00",
      notes: "Reservar cita en Apple Store o servicio técnico autorizado. AppleCare+ disponible.",
    },
    specs: [
      { label: "Pantalla", value: "6.1\" Super Retina XDR ProMotion 120Hz" },
      { label: "Chip", value: "A17 Pro (3nm)" },
      { label: "Almacenamiento", value: "256GB" },
      { label: "Cámara principal", value: "48 MP f/1.78" },
      { label: "Batería", value: "Hasta 23h reproducción vídeo" },
    ],
    createdAt: new Date("2024-09-21"),
    updatedAt: new Date(),
  },
  {
    id: "prod-2",
    userId: "user-1",
    categoryId: "cat-audio",
    category: mockCategories[6],
    brand: "Apple",
    model: "AirPods Pro",
    variant: "2ª generación USB-C",
    condition: "VERY_GOOD",
    purchaseDate: new Date("2024-01-15"),
    purchasePrice: 279,
    purchaseStore: "MediaMarkt",
    proofOfPurchaseUrl: "/mock/ticket-airpods.jpg",
    warrantyEndDate: new Date("2026-01-15"),
    photos: [
      "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800",
    ],
    accessories: { "Estuche de carga": true, "Almohadillas (3 tamaños)": true, "Cable USB-C": true, "Caja": true },
    estimatedValue: 185,
    estimatedValueUpdatedAt: new Date(),
    // === INFORMACIÓN ENRIQUECIDA POR IA ===
    resaleValue: {
      percentage: 66,
      minPrice: 165,
      maxPrice: 200,
      marketTrend: "stable",
      notes: "Producto muy demandado. El estado de la batería afecta al precio.",
    },
    manualUrl: "https://support.apple.com/es-es/guide/airpods/welcome/web",
    warrantyContact: {
      phone: "900 150 503",
      url: "https://support.apple.com/es-es/airpods/repair",
      hours: "L-V 9:00-21:00, S 9:00-18:00",
      notes: "Si la batería está degradada, Apple ofrece reemplazo a precio reducido.",
    },
    specs: [
      { label: "Chip", value: "H2" },
      { label: "Cancelación de ruido", value: "Activa adaptativa" },
      { label: "Audio espacial", value: "Sí, con seguimiento de cabeza" },
      { label: "Batería auriculares", value: "Hasta 6h (ANC activado)" },
      { label: "Batería total", value: "Hasta 30h con estuche" },
    ],
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date(),
  },
  {
    id: "prod-3",
    userId: "user-1",
    categoryId: "cat-consoles",
    category: mockCategories[5],
    brand: "Sony",
    model: "PlayStation 5",
    variant: "Digital Edition",
    condition: "GOOD",
    purchaseDate: new Date("2023-03-10"),
    purchasePrice: 449,
    purchaseStore: "Amazon",
    warrantyEndDate: new Date("2025-03-10"),
    serialLast4: "3291",
    photos: [
      "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800",
    ],
    accessories: { "Mando DualSense": true, "Cable HDMI": true, "Cable alimentación": true, "Base vertical": false, "Caja": false },
    estimatedValue: 320,
    estimatedValueUpdatedAt: new Date(),
    // === INFORMACIÓN ENRIQUECIDA POR IA ===
    resaleValue: {
      percentage: 71,
      minPrice: 290,
      maxPrice: 350,
      marketTrend: "falling",
      notes: "La PS5 Slim ha reducido ligeramente el valor del modelo original.",
    },
    manualUrl: "https://www.playstation.com/es-es/support/hardware/ps5/",
    warrantyContact: {
      phone: "900 102 102",
      url: "https://www.playstation.com/es-es/support/",
      hours: "L-V 10:00-19:00",
      notes: "Soporte online 24/7 disponible. Reparación por correo.",
    },
    specs: [
      { label: "CPU", value: "AMD Zen 2, 8 núcleos a 3.5GHz" },
      { label: "GPU", value: "10.28 TFLOPS, RDNA 2" },
      { label: "RAM", value: "16GB GDDR6" },
      { label: "Almacenamiento", value: "825GB SSD NVMe" },
      { label: "Resolución", value: "Hasta 4K 120fps / 8K" },
    ],
    createdAt: new Date("2023-03-11"),
    updatedAt: new Date(),
  },
  {
    id: "prod-4",
    userId: "user-1",
    categoryId: "cat-tablets",
    category: mockCategories[1],
    brand: "Apple",
    model: "iPad Pro 12.9\"",
    variant: "M2 256GB WiFi",
    condition: "LIKE_NEW",
    purchaseDate: new Date("2024-06-01"),
    purchasePrice: 1449,
    purchaseStore: "El Corte Inglés",
    proofOfPurchaseUrl: "/mock/ticket-ipad.jpg",
    warrantyEndDate: new Date("2026-06-01"),
    serialLast4: "8876",
    photos: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800",
    ],
    accessories: { "Cargador 20W": true, "Cable USB-C": true, "Magic Keyboard": true, "Apple Pencil 2": true, "Caja": true },
    estimatedValue: 1150,
    estimatedValueUpdatedAt: new Date(),
    // === INFORMACIÓN ENRIQUECIDA POR IA ===
    resaleValue: {
      percentage: 79,
      minPrice: 1050,
      maxPrice: 1250,
      marketTrend: "stable",
      notes: "Excelente retención de valor. Los accesorios aumentan significativamente el precio.",
    },
    manualUrl: "https://support.apple.com/es-es/guide/ipad/welcome/ipados",
    warrantyContact: {
      phone: "900 150 503",
      url: "https://support.apple.com/es-es/ipad/repair",
      hours: "L-V 9:00-21:00, S 9:00-18:00",
      notes: "AppleCare+ extiende la garantía 2 años adicionales.",
    },
    specs: [
      { label: "Pantalla", value: "12.9\" Liquid Retina XDR mini-LED" },
      { label: "Chip", value: "Apple M2 (8 núcleos CPU, 10 GPU)" },
      { label: "Almacenamiento", value: "256GB" },
      { label: "Cámara trasera", value: "12MP + 10MP Ultra Angular + LiDAR" },
      { label: "Face ID", value: "Sí" },
    ],
    createdAt: new Date("2024-06-02"),
    updatedAt: new Date(),
  },
  {
    id: "prod-5",
    userId: "user-1",
    categoryId: "cat-wearables",
    category: mockCategories[7],
    brand: "Apple",
    model: "Apple Watch Ultra 2",
    variant: "49mm Titanio",
    condition: "NEW",
    purchaseDate: new Date("2024-11-15"),
    purchasePrice: 899,
    purchaseStore: "Apple Store Online",
    proofOfPurchaseUrl: "/mock/ticket-watch.jpg",
    warrantyEndDate: new Date("2026-11-15"),
    serialLast4: "4412",
    photos: [
      "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=800",
    ],
    accessories: { "Cargador magnético": true, "Correa Alpine Loop": true, "Caja": true },
    estimatedValue: 780,
    estimatedValueUpdatedAt: new Date(),
    // === INFORMACIÓN ENRIQUECIDA POR IA ===
    resaleValue: {
      percentage: 87,
      minPrice: 720,
      maxPrice: 820,
      marketTrend: "stable",
      notes: "Modelo premium con excelente retención de valor. Alta demanda entre deportistas.",
    },
    manualUrl: "https://support.apple.com/es-es/guide/watch/welcome/watchos",
    warrantyContact: {
      phone: "900 150 503",
      url: "https://support.apple.com/es-es/watch/repair",
      hours: "L-V 9:00-21:00, S 9:00-18:00",
      notes: "Reemplazo de batería disponible por 105€ fuera de garantía.",
    },
    specs: [
      { label: "Pantalla", value: "49mm OLED siempre activa, 3000 nits" },
      { label: "Chip", value: "S9 SiP con doble núcleo" },
      { label: "Material", value: "Titanio grado aeroespacial" },
      { label: "Resistencia al agua", value: "100m / EN 13319" },
      { label: "Batería", value: "Hasta 36h (72h en bajo consumo)" },
    ],
    createdAt: new Date("2024-11-16"),
    updatedAt: new Date(),
  },
];

// ==========================================
// LISTINGS (Marketplace)
// ==========================================

export const mockListings: Listing[] = [
  {
    id: "list-1",
    productId: undefined,
    sellerId: "user-2",
    categoryId: "cat-smartphones",
    category: mockCategories[0],
    title: "iPhone 14 Pro Max 256GB - Impecable",
    description: "Vendido por actualización. Siempre con funda y protector de pantalla. Sin ningún rasguño. Batería al 94%. Incluye cargador original y caja.",
    price: 899,
    location: "Madrid",
    shippingEnabled: true,
    shippingCost: 5.99,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: [
      "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=800",
      "https://images.unsplash.com/photo-1591337676887-a217a6970a8a?w=800",
    ],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    viewCount: 234,
    favoriteCount: 18,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-2",
    sellerId: "user-3",
    categoryId: "cat-laptops",
    category: mockCategories[2],
    title: "MacBook Air M2 13\" 512GB - Midnight",
    description: "Comprado hace 8 meses para teletrabajo pero apenas lo he usado. Menos de 50 ciclos de batería. Incluye cargador MagSafe y caja original.",
    price: 1149,
    location: "Barcelona",
    shippingEnabled: true,
    shippingCost: 8.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800",
    ],
    isBoosted: false,
    viewCount: 156,
    favoriteCount: 12,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-3",
    sellerId: "user-4",
    categoryId: "cat-consoles",
    category: mockCategories[3],
    title: "Nintendo Switch OLED + 3 juegos",
    description: "Nintendo Switch modelo OLED en blanco. Incluye base, Joy-Cons y 3 juegos: Zelda TOTK, Mario Kart 8 y Animal Crossing. Todo en perfecto estado.",
    price: 320,
    location: "Valencia",
    shippingEnabled: true,
    shippingCost: 6.99,
    verificationLevel: "LEVEL_0",
    hasVerifiedPurchase: false,
    hasValidWarranty: false,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: [
      "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800",
    ],
    isBoosted: false,
    viewCount: 89,
    favoriteCount: 7,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-4",
    sellerId: "user-5",
    categoryId: "cat-audio",
    category: mockCategories[4],
    title: "Sony WH-1000XM5 - Negros",
    description: "Los mejores auriculares con cancelación de ruido. Comprados hace 6 meses, usados solo para viajes. Incluyen estuche, cable y cargador.",
    price: 275,
    location: "Sevilla",
    shippingEnabled: true,
    shippingCost: 4.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: [
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800",
    ],
    isBoosted: false,
    viewCount: 112,
    favoriteCount: 9,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-5",
    sellerId: "user-6",
    categoryId: "cat-wearables",
    category: mockCategories[5],
    title: "Apple Watch Series 9 45mm GPS",
    description: "Apple Watch Series 9 en color Midnight. Batería al 100%. Incluye correa deportiva original y cargador magnético.",
    price: 369,
    location: "Bilbao",
    shippingEnabled: true,
    shippingCost: 4.99,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: [
      "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=800",
    ],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    viewCount: 178,
    favoriteCount: 15,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-6",
    sellerId: "user-7",
    categoryId: "cat-smartphones",
    category: mockCategories[0],
    title: "Samsung Galaxy S24 Ultra 512GB",
    description: "Samsung Galaxy S24 Ultra en Titanium Gray. Incluye S Pen, cargador 45W y funda original Samsung. Sin marcas de uso.",
    price: 1099,
    location: "Málaga",
    shippingEnabled: true,
    shippingCost: 5.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: [
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800",
    ],
    isBoosted: false,
    viewCount: 201,
    favoriteCount: 22,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
];

// ==========================================
// CONVERSATIONS & MESSAGES
// ==========================================

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    listingId: "list-1",
    listing: mockListings[0],
    buyerId: "user-1",
    sellerId: "user-2",
    currentOffer: 850,
    offerStatus: "pending",
    messages: [
      {
        id: "msg-1",
        conversationId: "conv-1",
        senderId: "user-1",
        text: "Hola! Sigue disponible el iPhone?",
        isOffer: false,
        isSystemMessage: false,
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
      {
        id: "msg-2",
        conversationId: "conv-1",
        senderId: "user-2",
        text: "Hola! Sí, todavía lo tengo disponible.",
        isOffer: false,
        isSystemMessage: false,
        createdAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000),
      },
      {
        id: "msg-3",
        conversationId: "conv-1",
        senderId: "user-1",
        text: "Te ofrezco 850€",
        isOffer: true,
        offerAmount: 850,
        isSystemMessage: false,
        createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
];

// ==========================================
// ORDERS
// ==========================================

export const mockOrders: Order[] = [
  {
    id: "order-1",
    listingId: "list-old-1",
    buyerId: "user-1",
    sellerId: "user-8",
    amount: 650,
    shippingAmount: 5.99,
    feeMarketplace: 45.5,
    feeProtection: 13,
    total: 714.49,
    sellerPayout: 604.5,
    status: "ACCEPTED",
    trackingNumber: "MRW123456789",
    carrier: "MRW",
    isLocalPickup: false,
    paidAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    shippedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    deliveredAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    acceptedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    releasedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
];

// ==========================================
// ALERTS
// ==========================================

export const mockAlerts: Alert[] = [
  {
    id: "alert-1",
    userId: "user-1",
    productId: "prod-1",
    type: "sell_now",
    title: "Buen momento para vender",
    message: "Tu iPhone 15 Pro mantiene buen valor. Ahora puedes obtener 1.050€",
    isRead: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "alert-2",
    userId: "user-1",
    productId: "prod-3",
    type: "warranty_expiring",
    title: "Garantía próxima a expirar",
    message: "La garantía de tu PlayStation 5 expira en 60 días",
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "alert-3",
    userId: "user-1",
    productId: "prod-2",
    type: "price_drop",
    title: "Bajada de precio detectada",
    message: "Los AirPods Pro han bajado un 8% este mes en el mercado",
    isRead: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
];

// ==========================================
// HELPER FUNCTIONS
// ==========================================

export function getProductById(id: string): Product | undefined {
  return mockProducts.find((p) => p.id === id);
}

export function getListingById(id: string): Listing | undefined {
  return mockListings.find((l) => l.id === id);
}

export function getCategoryById(id: string): Category | undefined {
  return mockCategories.find((c) => c.id === id);
}

export function getConversationById(id: string): Conversation | undefined {
  return mockConversations.find((c) => c.id === id);
}

// Calculate total wallet value
export function calculateWalletValue(products: Product[]): number {
  return products.reduce((total, product) => total + (product.estimatedValue || 0), 0);
}

// Get price recommendation based on estimated value
export function getPriceRecommendations(estimatedValue: number) {
  return {
    fast: Math.round(estimatedValue * 0.85),
    fair: Math.round(estimatedValue * 0.95),
    max: Math.round(estimatedValue * 1.05),
  };
}
