import { Category, Product, Listing, Conversation, Message, Order, Alert, SellerProfile } from "@/types";

// ==========================================
// SELLERS / USUARIOS MOCK
// ==========================================

export const mockSellers: SellerProfile[] = [
  {
    id: "seller-1",
    firstName: "Carlos",
    lastName: "García",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    location: "Madrid",
    totalSales: 47,
    totalProducts: 12,
    rating: 4.9,
    reviewCount: 43,
    responseTime: "< 1 hora",
    responseRate: 98,
    isVerified: true,
    isIdentityVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    memberSince: new Date("2022-03-15"),
    lastActive: new Date(Date.now() - 2 * 60 * 60 * 1000), // Hace 2 horas
    bio: "Entusiasta de la tecnología. Todos mis productos están en perfecto estado y con factura original.",
  },
  {
    id: "seller-2",
    firstName: "Laura",
    lastName: "Martínez",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
    location: "Barcelona",
    totalSales: 89,
    totalProducts: 23,
    rating: 4.8,
    reviewCount: 76,
    responseTime: "< 30 min",
    responseRate: 100,
    isVerified: true,
    isIdentityVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    memberSince: new Date("2021-08-20"),
    lastActive: new Date(Date.now() - 30 * 60 * 1000), // Hace 30 min
    bio: "Mamá tech. Vendo productos que ya no uso. Envío rápido y seguro 📦",
  },
  {
    id: "seller-3",
    firstName: "Miguel",
    lastName: "Rodríguez",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    location: "Valencia",
    totalSales: 23,
    totalProducts: 8,
    rating: 4.7,
    reviewCount: 19,
    responseTime: "< 2 horas",
    responseRate: 95,
    isVerified: true,
    isIdentityVerified: false,
    isEmailVerified: true,
    isPhoneVerified: true,
    memberSince: new Date("2023-01-10"),
    lastActive: new Date(Date.now() - 5 * 60 * 60 * 1000), // Hace 5 horas
    bio: "Gamer y coleccionista. Solo vendo lo que ya no necesito.",
  },
  {
    id: "seller-4",
    firstName: "Ana",
    lastName: "López",
    avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    location: "Sevilla",
    totalSales: 156,
    totalProducts: 45,
    rating: 5.0,
    reviewCount: 142,
    responseTime: "< 15 min",
    responseRate: 100,
    isVerified: true,
    isIdentityVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    memberSince: new Date("2020-05-12"),
    lastActive: new Date(Date.now() - 10 * 60 * 1000), // Hace 10 min
    bio: "Vendedora profesional. Garantizo satisfacción total o devolución. ⭐️⭐️⭐️⭐️⭐️",
  },
  {
    id: "seller-5",
    firstName: "Pablo",
    lastName: "Fernández",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    location: "Bilbao",
    totalSales: 34,
    totalProducts: 15,
    rating: 4.6,
    reviewCount: 28,
    responseTime: "< 4 horas",
    responseRate: 88,
    isVerified: true,
    isIdentityVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    memberSince: new Date("2022-11-03"),
    lastActive: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // Hace 1 día
    bio: "Deportista y aventurero. Equipo de calidad a buenos precios.",
  },
  {
    id: "seller-6",
    firstName: "Elena",
    lastName: "Sánchez",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
    location: "Málaga",
    totalSales: 67,
    totalProducts: 19,
    rating: 4.9,
    reviewCount: 58,
    responseTime: "< 1 hora",
    responseRate: 97,
    isVerified: true,
    isIdentityVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    memberSince: new Date("2021-12-08"),
    lastActive: new Date(Date.now() - 45 * 60 * 1000), // Hace 45 min
    bio: "Fashionista y amante de los relojes. Autenticidad garantizada.",
  },
  {
    id: "seller-7",
    firstName: "Javier",
    lastName: "Ruiz",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    location: "Zaragoza",
    totalSales: 12,
    totalProducts: 5,
    rating: 4.5,
    reviewCount: 9,
    responseTime: "< 6 horas",
    responseRate: 82,
    isVerified: false,
    isIdentityVerified: false,
    isEmailVerified: true,
    isPhoneVerified: true,
    memberSince: new Date("2024-02-20"),
    lastActive: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // Hace 3 días
    bio: "Vendedor ocasional. Buenos productos a buen precio.",
  },
  {
    id: "seller-8",
    firstName: "María",
    lastName: "Torres",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
    location: "Alicante",
    totalSales: 78,
    totalProducts: 28,
    rating: 4.8,
    reviewCount: 65,
    responseTime: "< 2 horas",
    responseRate: 94,
    isVerified: true,
    isIdentityVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    memberSince: new Date("2021-06-15"),
    lastActive: new Date(Date.now() - 3 * 60 * 60 * 1000), // Hace 3 horas
    bio: "Mamá de dos. Vendo artículos de bebé en excelente estado.",
  },
  {
    id: "seller-9",
    firstName: "Daniel",
    lastName: "Jiménez",
    avatarUrl: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=150&h=150&fit=crop&crop=face",
    location: "Granada",
    totalSales: 203,
    totalProducts: 67,
    rating: 4.9,
    reviewCount: 187,
    responseTime: "< 30 min",
    responseRate: 99,
    isVerified: true,
    isIdentityVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    memberSince: new Date("2019-09-01"),
    lastActive: new Date(Date.now() - 15 * 60 * 1000), // Hace 15 min
    bio: "Ingeniero informático. Especializado en Apple y fotografía profesional.",
  },
  {
    id: "seller-10",
    firstName: "Sofía",
    lastName: "Moreno",
    avatarUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&h=150&fit=crop&crop=face",
    location: "Murcia",
    totalSales: 45,
    totalProducts: 14,
    rating: 4.7,
    reviewCount: 38,
    responseTime: "< 3 horas",
    responseRate: 91,
    isVerified: true,
    isIdentityVerified: false,
    isEmailVerified: true,
    isPhoneVerified: true,
    memberSince: new Date("2022-07-22"),
    lastActive: new Date(Date.now() - 8 * 60 * 60 * 1000), // Hace 8 horas
    bio: "Diseñadora gráfica. Vendo equipos creativos y electrónica.",
  },
  {
    id: "seller-11",
    firstName: "Alejandro",
    lastName: "Navarro",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face",
    location: "Valladolid",
    totalSales: 89,
    totalProducts: 31,
    rating: 4.8,
    reviewCount: 74,
    responseTime: "< 1 hora",
    responseRate: 96,
    isVerified: true,
    isIdentityVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    memberSince: new Date("2020-11-18"),
    lastActive: new Date(Date.now() - 1 * 60 * 60 * 1000), // Hace 1 hora
    bio: "Músico profesional. Instrumentos de calidad profesional.",
  },
  {
    id: "seller-12",
    firstName: "Carmen",
    lastName: "Vega",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face",
    location: "A Coruña",
    totalSales: 134,
    totalProducts: 42,
    rating: 5.0,
    reviewCount: 121,
    responseTime: "< 20 min",
    responseRate: 100,
    isVerified: true,
    isIdentityVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    memberSince: new Date("2020-02-14"),
    lastActive: new Date(Date.now() - 5 * 60 * 1000), // Hace 5 min
    bio: "Coleccionista de relojes y bolsos de lujo. Solo originales certificados.",
  },
];

// Helper para obtener un seller por ID
export const getSellerById = (id: string): SellerProfile | undefined => {
  return mockSellers.find(s => s.id === id);
};

// ==========================================
// CATEGORY GROUPS (para UI agrupada)
// ==========================================

export type CategoryGroup = {
  id: string;
  name: string;
  icon: string;
  categoryIds: string[];
};

export const categoryGroups: CategoryGroup[] = [
  {
    id: "grp-tech",
    name: "Tecnología",
    icon: "💻",
    categoryIds: ["cat-smartphones", "cat-tablets", "cat-laptops", "cat-desktops", "cat-monitors", "cat-cameras", "cat-networking", "cat-storage", "cat-peripherals"],
  },
  {
    id: "grp-audio-video",
    name: "Audio y Video",
    icon: "🎧",
    categoryIds: ["cat-audio", "cat-tv", "cat-projectors"],
  },
  {
    id: "grp-gaming",
    name: "Gaming",
    icon: "🎮",
    categoryIds: ["cat-consoles", "cat-gaming"],
  },
  {
    id: "grp-wearables",
    name: "Wearables",
    icon: "⌚",
    categoryIds: ["cat-wearables"],
  },
  {
    id: "grp-appliances",
    name: "Electrodomésticos",
    icon: "🏠",
    categoryIds: ["cat-appliances-large", "cat-appliances-small", "cat-climate"],
  },
  {
    id: "grp-mobility",
    name: "Movilidad",
    icon: "🚲",
    categoryIds: ["cat-ebikes", "cat-scooters", "cat-drones"],
  },
  {
    id: "grp-baby",
    name: "Bebés y Niños",
    icon: "👶",
    categoryIds: ["cat-baby-strollers", "cat-baby-car-seats", "cat-baby-furniture", "cat-toys"],
  },
  {
    id: "grp-home",
    name: "Hogar",
    icon: "🏡",
    categoryIds: ["cat-furniture", "cat-garden", "cat-lighting", "cat-home-decor"],
  },
  {
    id: "grp-sports",
    name: "Deporte",
    icon: "⚽",
    categoryIds: ["cat-fitness", "cat-bikes", "cat-sports", "cat-outdoor"],
  },
  {
    id: "grp-fashion",
    name: "Moda y Lujo",
    icon: "👜",
    categoryIds: ["cat-fashion-luxury", "cat-watches-jewelry", "cat-bags"],
  },
  {
    id: "grp-music",
    name: "Música",
    icon: "🎸",
    categoryIds: ["cat-instruments", "cat-music-equipment"],
  },
  {
    id: "grp-tools",
    name: "Herramientas",
    icon: "🔧",
    categoryIds: ["cat-tools", "cat-power-tools"],
  },
  {
    id: "grp-vehicles",
    name: "Vehículos",
    icon: "🏍️",
    categoryIds: ["cat-motorcycles", "cat-car-parts"],
  },
  {
    id: "grp-other",
    name: "Otros",
    icon: "📦",
    categoryIds: ["cat-collectibles", "cat-books-media", "cat-other"],
  },
];

// ==========================================
// CATEGORIES
// ==========================================

export const mockCategories: Category[] = [
  // === ELECTRÓNICA DE CONSUMO ===
  {
    id: "cat-smartphones",
    name: "Smartphones",
    slug: "smartphones",
    icon: "📱",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-tablets",
    name: "Tablets",
    slug: "tablets",
    icon: "📲",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-laptops",
    name: "Portátiles",
    slug: "laptops",
    icon: "💻",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-desktops",
    name: "Ordenadores de sobremesa",
    slug: "desktops",
    icon: "🖥️",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-monitors",
    name: "Monitores",
    slug: "monitors",
    icon: "🖥️",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-consoles",
    name: "Consolas",
    slug: "consoles",
    icon: "🎮",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-audio",
    name: "Audio",
    slug: "audio",
    icon: "🎧",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-wearables",
    name: "Wearables",
    slug: "wearables",
    icon: "⌚",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-cameras",
    name: "Cámaras y Fotografía",
    slug: "cameras",
    icon: "📷",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-tv",
    name: "Televisores",
    slug: "tv",
    icon: "📺",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-projectors",
    name: "Proyectores",
    slug: "projectors",
    icon: "📽️",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  // === ELECTRODOMÉSTICOS ===
  {
    id: "cat-appliances-large",
    name: "Grandes Electrodomésticos",
    slug: "appliances-large",
    icon: "🧊",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-appliances-small",
    name: "Pequeños Electrodomésticos",
    slug: "appliances-small",
    icon: "🍳",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-climate",
    name: "Climatización",
    slug: "climate",
    icon: "❄️",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  // === MOVILIDAD ===
  {
    id: "cat-ebikes",
    name: "Bicicletas Eléctricas",
    slug: "ebikes",
    icon: "🚲",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-scooters",
    name: "Patinetes Eléctricos",
    slug: "scooters",
    icon: "🛴",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  // === OTROS ===
  {
    id: "cat-drones",
    name: "Drones",
    slug: "drones",
    icon: "🚁",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-gaming",
    name: "Accesorios Gaming",
    slug: "gaming",
    icon: "🕹️",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-networking",
    name: "Redes y Conectividad",
    slug: "networking",
    icon: "📡",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-storage",
    name: "Almacenamiento",
    slug: "storage",
    icon: "💾",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-peripherals",
    name: "Periféricos",
    slug: "peripherals",
    icon: "⌨️",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-other-electronics",
    name: "Otros Electrónica",
    slug: "other-electronics",
    icon: "🔌",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  // === BEBÉS Y NIÑOS ===
  {
    id: "cat-baby-strollers",
    name: "Carritos y Sillas de Paseo",
    slug: "baby-strollers",
    icon: "👶",
    minPhotos: 3,
    requiresTicket: true,
    requiresSerial: false,
  },
  {
    id: "cat-baby-car-seats",
    name: "Sillas de Coche",
    slug: "baby-car-seats",
    icon: "🚗",
    minPhotos: 3,
    requiresTicket: true,
    requiresSerial: true,
  },
  {
    id: "cat-baby-furniture",
    name: "Mobiliario Bebé",
    slug: "baby-furniture",
    icon: "🛒",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-toys",
    name: "Juguetes",
    slug: "toys",
    icon: "🧸",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  // === HOGAR Y JARDÍN ===
  {
    id: "cat-furniture",
    name: "Muebles",
    slug: "furniture",
    icon: "🪑",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-garden",
    name: "Jardín y Exterior",
    slug: "garden",
    icon: "🌱",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-lighting",
    name: "Iluminación",
    slug: "lighting",
    icon: "💡",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-home-decor",
    name: "Decoración",
    slug: "home-decor",
    icon: "🖼️",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  // === DEPORTE Y FITNESS ===
  {
    id: "cat-fitness",
    name: "Fitness y Gimnasio",
    slug: "fitness",
    icon: "🏋️",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-bikes",
    name: "Bicicletas",
    slug: "bikes",
    icon: "🚴",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-sports",
    name: "Equipamiento Deportivo",
    slug: "sports",
    icon: "⚽",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-outdoor",
    name: "Outdoor y Camping",
    slug: "outdoor",
    icon: "⛺",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  // === MODA Y ACCESORIOS ===
  {
    id: "cat-fashion-luxury",
    name: "Moda de Lujo",
    slug: "fashion-luxury",
    icon: "👜",
    minPhotos: 4,
    requiresTicket: true,
    requiresSerial: true,
  },
  {
    id: "cat-watches-jewelry",
    name: "Relojes y Joyería",
    slug: "watches-jewelry",
    icon: "💎",
    minPhotos: 4,
    requiresTicket: true,
    requiresSerial: true,
  },
  {
    id: "cat-bags",
    name: "Bolsos y Maletas",
    slug: "bags",
    icon: "🧳",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: false,
  },
  // === INSTRUMENTOS MUSICALES ===
  {
    id: "cat-instruments",
    name: "Instrumentos Musicales",
    slug: "instruments",
    icon: "🎸",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: true,
  },
  {
    id: "cat-music-equipment",
    name: "Equipos de Música/DJ",
    slug: "music-equipment",
    icon: "🎛️",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  // === HERRAMIENTAS ===
  {
    id: "cat-tools",
    name: "Herramientas",
    slug: "tools",
    icon: "🔧",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-power-tools",
    name: "Herramientas Eléctricas",
    slug: "power-tools",
    icon: "🔨",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: true,
  },
  // === VEHÍCULOS Y MOTOR ===
  {
    id: "cat-motorcycles",
    name: "Motos y Ciclomotores",
    slug: "motorcycles",
    icon: "🏍️",
    minPhotos: 5,
    requiresTicket: true,
    requiresSerial: true,
  },
  {
    id: "cat-car-parts",
    name: "Recambios y Accesorios Coche",
    slug: "car-parts",
    icon: "🚙",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
  // === OTROS ===
  {
    id: "cat-collectibles",
    name: "Coleccionismo",
    slug: "collectibles",
    icon: "🏆",
    minPhotos: 3,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-books-media",
    name: "Libros y Medios",
    slug: "books-media",
    icon: "📚",
    minPhotos: 1,
    requiresTicket: false,
    requiresSerial: false,
  },
  {
    id: "cat-other",
    name: "Otros",
    slug: "other",
    icon: "📦",
    minPhotos: 2,
    requiresTicket: false,
    requiresSerial: false,
  },
];

// ==========================================
// PRODUCTS (Wallet)
// ==========================================

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    userId: "user-1",
    categoryId: "cat-smartphones",
    category: mockCategories[0],
    brand: "Apple",
    model: "iPhone 15 Pro",
    variant: "256GB Titanio Natural",
    condition: "LIKE_NEW",
    purchaseDate: new Date("2024-09-20"),
    purchasePrice: 1329,
    purchaseStore: "Apple Store",
    proofOfPurchaseUrl: "/mock/ticket-iphone.jpg",
    warrantyEndDate: new Date("2026-09-20"),
    imeiLast4: "7842",
    photos: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800",
      "https://images.unsplash.com/photo-1696426051872-0ecc5cc0fba4?w=800",
    ],
    accessories: { "Cable USB-C": true, "Caja original": true, "Cargador": false, "SIM tool": true },
    estimatedValue: 1050,
    estimatedValueUpdatedAt: new Date(),
    // === INFORMACIÓN ENRIQUECIDA POR IA ===
    resaleValue: {
      percentage: 79,
      minPrice: 980,
      maxPrice: 1120,
      marketTrend: "stable",
      notes: "Alta demanda, modelo reciente. Mantiene muy bien el valor.",
    },
    manualUrl: "https://support.apple.com/es-es/guide/iphone/welcome/ios",
    warrantyContact: {
      phone: "900 150 503",
      email: undefined,
      url: "https://support.apple.com/es-es/repair",
      hours: "L-V 9:00-21:00, S 9:00-18:00",
      notes: "Reservar cita en Apple Store o servicio técnico autorizado. AppleCare+ disponible.",
    },
    specs: [
      { label: "Pantalla", value: "6.1\" Super Retina XDR ProMotion 120Hz" },
      { label: "Chip", value: "A17 Pro (3nm)" },
      { label: "Almacenamiento", value: "256GB" },
      { label: "Cámara principal", value: "48 MP f/1.78" },
      { label: "Batería", value: "Hasta 23h reproducción vídeo" },
    ],
    createdAt: new Date("2024-09-21"),
    updatedAt: new Date(),
  },
  {
    id: "prod-2",
    userId: "user-1",
    categoryId: "cat-audio",
    category: mockCategories[6],
    brand: "Apple",
    model: "AirPods Pro",
    variant: "2ª generación USB-C",
    condition: "VERY_GOOD",
    purchaseDate: new Date("2024-01-15"),
    purchasePrice: 279,
    purchaseStore: "MediaMarkt",
    proofOfPurchaseUrl: "/mock/ticket-airpods.jpg",
    warrantyEndDate: new Date("2026-01-15"),
    photos: [
      "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800",
    ],
    accessories: { "Estuche de carga": true, "Almohadillas (3 tamaños)": true, "Cable USB-C": true, "Caja": true },
    estimatedValue: 185,
    estimatedValueUpdatedAt: new Date(),
    // === INFORMACIÓN ENRIQUECIDA POR IA ===
    resaleValue: {
      percentage: 66,
      minPrice: 165,
      maxPrice: 200,
      marketTrend: "stable",
      notes: "Producto muy demandado. El estado de la batería afecta al precio.",
    },
    manualUrl: "https://support.apple.com/es-es/guide/airpods/welcome/web",
    warrantyContact: {
      phone: "900 150 503",
      url: "https://support.apple.com/es-es/airpods/repair",
      hours: "L-V 9:00-21:00, S 9:00-18:00",
      notes: "Si la batería está degradada, Apple ofrece reemplazo a precio reducido.",
    },
    specs: [
      { label: "Chip", value: "H2" },
      { label: "Cancelación de ruido", value: "Activa adaptativa" },
      { label: "Audio espacial", value: "Sí, con seguimiento de cabeza" },
      { label: "Batería auriculares", value: "Hasta 6h (ANC activado)" },
      { label: "Batería total", value: "Hasta 30h con estuche" },
    ],
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date(),
  },
  {
    id: "prod-3",
    userId: "user-1",
    categoryId: "cat-consoles",
    category: mockCategories[5],
    brand: "Sony",
    model: "PlayStation 5",
    variant: "Digital Edition",
    condition: "GOOD",
    purchaseDate: new Date("2023-03-10"),
    purchasePrice: 449,
    purchaseStore: "Amazon",
    warrantyEndDate: new Date("2025-03-10"),
    serialLast4: "3291",
    photos: [
      "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800",
    ],
    accessories: { "Mando DualSense": true, "Cable HDMI": true, "Cable alimentación": true, "Base vertical": false, "Caja": false },
    estimatedValue: 320,
    estimatedValueUpdatedAt: new Date(),
    // === INFORMACIÓN ENRIQUECIDA POR IA ===
    resaleValue: {
      percentage: 71,
      minPrice: 290,
      maxPrice: 350,
      marketTrend: "falling",
      notes: "La PS5 Slim ha reducido ligeramente el valor del modelo original.",
    },
    manualUrl: "https://www.playstation.com/es-es/support/hardware/ps5/",
    warrantyContact: {
      phone: "900 102 102",
      url: "https://www.playstation.com/es-es/support/",
      hours: "L-V 10:00-19:00",
      notes: "Soporte online 24/7 disponible. Reparación por correo.",
    },
    specs: [
      { label: "CPU", value: "AMD Zen 2, 8 núcleos a 3.5GHz" },
      { label: "GPU", value: "10.28 TFLOPS, RDNA 2" },
      { label: "RAM", value: "16GB GDDR6" },
      { label: "Almacenamiento", value: "825GB SSD NVMe" },
      { label: "Resolución", value: "Hasta 4K 120fps / 8K" },
    ],
    createdAt: new Date("2023-03-11"),
    updatedAt: new Date(),
  },
  {
    id: "prod-4",
    userId: "user-1",
    categoryId: "cat-tablets",
    category: mockCategories[1],
    brand: "Apple",
    model: "iPad Pro 12.9\"",
    variant: "M2 256GB WiFi",
    condition: "LIKE_NEW",
    purchaseDate: new Date("2024-06-01"),
    purchasePrice: 1449,
    purchaseStore: "El Corte Inglés",
    proofOfPurchaseUrl: "/mock/ticket-ipad.jpg",
    warrantyEndDate: new Date("2026-06-01"),
    serialLast4: "8876",
    photos: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800",
    ],
    accessories: { "Cargador 20W": true, "Cable USB-C": true, "Magic Keyboard": true, "Apple Pencil 2": true, "Caja": true },
    estimatedValue: 1150,
    estimatedValueUpdatedAt: new Date(),
    // === INFORMACIÓN ENRIQUECIDA POR IA ===
    resaleValue: {
      percentage: 79,
      minPrice: 1050,
      maxPrice: 1250,
      marketTrend: "stable",
      notes: "Excelente retención de valor. Los accesorios aumentan significativamente el precio.",
    },
    manualUrl: "https://support.apple.com/es-es/guide/ipad/welcome/ipados",
    warrantyContact: {
      phone: "900 150 503",
      url: "https://support.apple.com/es-es/ipad/repair",
      hours: "L-V 9:00-21:00, S 9:00-18:00",
      notes: "AppleCare+ extiende la garantía 2 años adicionales.",
    },
    specs: [
      { label: "Pantalla", value: "12.9\" Liquid Retina XDR mini-LED" },
      { label: "Chip", value: "Apple M2 (8 núcleos CPU, 10 GPU)" },
      { label: "Almacenamiento", value: "256GB" },
      { label: "Cámara trasera", value: "12MP + 10MP Ultra Angular + LiDAR" },
      { label: "Face ID", value: "Sí" },
    ],
    createdAt: new Date("2024-06-02"),
    updatedAt: new Date(),
  },
  {
    id: "prod-5",
    userId: "user-1",
    categoryId: "cat-wearables",
    category: mockCategories[7],
    brand: "Apple",
    model: "Apple Watch Ultra 2",
    variant: "49mm Titanio",
    condition: "NEW",
    purchaseDate: new Date("2024-11-15"),
    purchasePrice: 899,
    purchaseStore: "Apple Store Online",
    proofOfPurchaseUrl: "/mock/ticket-watch.jpg",
    warrantyEndDate: new Date("2026-11-15"),
    serialLast4: "4412",
    photos: [
      "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=800",
    ],
    accessories: { "Cargador magnético": true, "Correa Alpine Loop": true, "Caja": true },
    estimatedValue: 780,
    estimatedValueUpdatedAt: new Date(),
    // === INFORMACIÓN ENRIQUECIDA POR IA ===
    resaleValue: {
      percentage: 87,
      minPrice: 720,
      maxPrice: 820,
      marketTrend: "stable",
      notes: "Modelo premium con excelente retención de valor. Alta demanda entre deportistas.",
    },
    manualUrl: "https://support.apple.com/es-es/guide/watch/welcome/watchos",
    warrantyContact: {
      phone: "900 150 503",
      url: "https://support.apple.com/es-es/watch/repair",
      hours: "L-V 9:00-21:00, S 9:00-18:00",
      notes: "Reemplazo de batería disponible por 105€ fuera de garantía.",
    },
    specs: [
      { label: "Pantalla", value: "49mm OLED siempre activa, 3000 nits" },
      { label: "Chip", value: "S9 SiP con doble núcleo" },
      { label: "Material", value: "Titanio grado aeroespacial" },
      { label: "Resistencia al agua", value: "100m / EN 13319" },
      { label: "Batería", value: "Hasta 36h (72h en bajo consumo)" },
    ],
    createdAt: new Date("2024-11-16"),
    updatedAt: new Date(),
  },
  // === MÁS PRODUCTOS DEL USUARIO PARA VENDER ===
  {
    id: "prod-6",
    userId: "user-1",
    categoryId: "cat-laptops",
    brand: "Apple",
    model: "MacBook Air",
    variant: "M2 13\" 256GB Midnight",
    condition: "VERY_GOOD",
    purchaseDate: new Date("2024-03-15"),
    purchasePrice: 1399,
    purchaseStore: "Amazon",
    proofOfPurchaseUrl: "/mock/ticket-macbook.jpg",
    warrantyEndDate: new Date("2026-03-15"),
    serialLast4: "2847",
    photos: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800",
    ],
    accessories: { "Cargador MagSafe 35W": true, "Cable USB-C a MagSafe": true, "Caja": true },
    estimatedValue: 1050,
    estimatedValueUpdatedAt: new Date(),
    resaleValue: {
      percentage: 75,
      minPrice: 980,
      maxPrice: 1100,
      marketTrend: "stable",
    },
    createdAt: new Date("2024-03-16"),
    updatedAt: new Date(),
  },
  {
    id: "prod-7",
    userId: "user-1",
    categoryId: "cat-cameras",
    brand: "Sony",
    model: "ZV-E10",
    variant: "Kit con 16-50mm",
    condition: "LIKE_NEW",
    purchaseDate: new Date("2024-07-20"),
    purchasePrice: 849,
    purchaseStore: "Foto K",
    proofOfPurchaseUrl: "/mock/ticket-sony.jpg",
    warrantyEndDate: new Date("2026-07-20"),
    serialLast4: "9234",
    photos: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800",
    ],
    accessories: { "Lente 16-50mm": true, "Batería extra": true, "Cargador": true, "Correa": true, "Caja": true },
    estimatedValue: 680,
    estimatedValueUpdatedAt: new Date(),
    resaleValue: {
      percentage: 80,
      minPrice: 620,
      maxPrice: 720,
      marketTrend: "stable",
    },
    createdAt: new Date("2024-07-21"),
    updatedAt: new Date(),
  },
  {
    id: "prod-8",
    userId: "user-1",
    categoryId: "cat-appliances-small",
    brand: "Dyson",
    model: "Airwrap Complete Long",
    variant: "Nickel/Copper",
    condition: "VERY_GOOD",
    purchaseDate: new Date("2024-05-10"),
    purchasePrice: 549,
    purchaseStore: "El Corte Inglés",
    proofOfPurchaseUrl: "/mock/ticket-dyson.jpg",
    warrantyEndDate: new Date("2026-05-10"),
    photos: [
      "https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=800",
    ],
    accessories: { "Accesorios completos": true, "Estuche": true, "Alfombra térmica": true },
    estimatedValue: 400,
    estimatedValueUpdatedAt: new Date(),
    resaleValue: {
      percentage: 73,
      minPrice: 350,
      maxPrice: 420,
      marketTrend: "stable",
    },
    createdAt: new Date("2024-05-11"),
    updatedAt: new Date(),
  },
  {
    id: "prod-9",
    userId: "user-1",
    categoryId: "cat-baby-strollers",
    brand: "Bugaboo",
    model: "Bee 6",
    variant: "Negro/Gris Melange",
    condition: "GOOD",
    purchaseDate: new Date("2023-09-01"),
    purchasePrice: 799,
    purchaseStore: "El Corte Inglés",
    warrantyEndDate: new Date("2025-09-01"),
    photos: [
      "https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800",
    ],
    accessories: { "Capota": true, "Barra delantera": true, "Saco de lluvia": true },
    estimatedValue: 450,
    estimatedValueUpdatedAt: new Date(),
    resaleValue: {
      percentage: 56,
      minPrice: 400,
      maxPrice: 500,
      marketTrend: "stable",
    },
    createdAt: new Date("2023-09-02"),
    updatedAt: new Date(),
  },
  {
    id: "prod-10",
    userId: "user-1",
    categoryId: "cat-drones",
    brand: "DJI",
    model: "Mini 3 Pro",
    variant: "Fly More Combo DJI RC",
    condition: "LIKE_NEW",
    purchaseDate: new Date("2024-08-15"),
    purchasePrice: 999,
    purchaseStore: "Amazon",
    proofOfPurchaseUrl: "/mock/ticket-dji.jpg",
    warrantyEndDate: new Date("2025-08-15"),
    serialLast4: "6721",
    photos: [
      "https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?w=800",
    ],
    accessories: { "3 Baterías": true, "Hub de carga": true, "Mando RC con pantalla": true, "Filtros ND": true, "Estuche": true },
    estimatedValue: 780,
    estimatedValueUpdatedAt: new Date(),
    resaleValue: {
      percentage: 78,
      minPrice: 720,
      maxPrice: 820,
      marketTrend: "stable",
    },
    createdAt: new Date("2024-08-16"),
    updatedAt: new Date(),
  },
  {
    id: "prod-11",
    userId: "user-1",
    categoryId: "cat-gaming",
    brand: "Razer",
    model: "Wolverine V2 Pro",
    variant: "Negro",
    condition: "VERY_GOOD",
    purchaseDate: new Date("2024-02-20"),
    purchasePrice: 299,
    purchaseStore: "PcComponentes",
    proofOfPurchaseUrl: "/mock/ticket-razer.jpg",
    warrantyEndDate: new Date("2026-02-20"),
    photos: [
      "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800",
    ],
    accessories: { "Receptor inalámbrico": true, "Cable USB-C": true, "Estuche": true },
    estimatedValue: 200,
    estimatedValueUpdatedAt: new Date(),
    resaleValue: {
      percentage: 67,
      minPrice: 180,
      maxPrice: 220,
      marketTrend: "falling",
    },
    createdAt: new Date("2024-02-21"),
    updatedAt: new Date(),
  },
  {
    id: "prod-12",
    userId: "user-1",
    categoryId: "cat-watches-jewelry",
    brand: "Tag Heuer",
    model: "Carrera Chronograph",
    variant: "Calibre Heuer 02",
    condition: "LIKE_NEW",
    purchaseDate: new Date("2023-12-25"),
    purchasePrice: 5500,
    purchaseStore: "Joyería Suiza",
    proofOfPurchaseUrl: "/mock/ticket-tagheuer.jpg",
    warrantyEndDate: new Date("2025-12-25"),
    serialLast4: "0847",
    photos: [
      "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800",
    ],
    accessories: { "Estuche original": true, "Certificado": true, "Eslabones extra": true },
    estimatedValue: 4500,
    estimatedValueUpdatedAt: new Date(),
    resaleValue: {
      percentage: 82,
      minPrice: 4200,
      maxPrice: 4800,
      marketTrend: "stable",
    },
    createdAt: new Date("2023-12-26"),
    updatedAt: new Date(),
  },
  {
    id: "prod-13",
    userId: "user-1",
    categoryId: "cat-instruments",
    brand: "Gibson",
    model: "Les Paul Standard '50s",
    variant: "Heritage Cherry Sunburst",
    condition: "VERY_GOOD",
    purchaseDate: new Date("2022-06-15"),
    purchasePrice: 2599,
    purchaseStore: "Thomann",
    warrantyEndDate: new Date("2024-06-15"),
    serialLast4: "1234",
    photos: [
      "https://images.unsplash.com/photo-1564186763535-ebb21ef5277f?w=800",
    ],
    accessories: { "Estuche rígido Gibson": true, "Certificado de autenticidad": true, "Correa Gibson": false },
    estimatedValue: 2100,
    estimatedValueUpdatedAt: new Date(),
    resaleValue: {
      percentage: 81,
      minPrice: 1950,
      maxPrice: 2200,
      marketTrend: "rising",
    },
    createdAt: new Date("2022-06-16"),
    updatedAt: new Date(),
  },
  {
    id: "prod-14",
    userId: "user-1",
    categoryId: "cat-fitness",
    brand: "Technogym",
    model: "MyRun",
    variant: "Treadmill",
    condition: "GOOD",
    purchaseDate: new Date("2023-01-10"),
    purchasePrice: 3500,
    purchaseStore: "Technogym Store",
    warrantyEndDate: new Date("2025-01-10"),
    photos: [
      "https://images.unsplash.com/photo-1591291621164-2c6367723315?w=800",
    ],
    accessories: { "Alfombrilla": true, "Manual": true },
    estimatedValue: 2200,
    estimatedValueUpdatedAt: new Date(),
    resaleValue: {
      percentage: 63,
      minPrice: 2000,
      maxPrice: 2400,
      marketTrend: "falling",
    },
    createdAt: new Date("2023-01-11"),
    updatedAt: new Date(),
  },
  {
    id: "prod-15",
    userId: "user-1",
    categoryId: "cat-scooters",
    brand: "Xiaomi",
    model: "Electric Scooter 4 Ultra",
    variant: "Negro",
    condition: "VERY_GOOD",
    purchaseDate: new Date("2024-04-01"),
    purchasePrice: 799,
    purchaseStore: "Mi Store",
    proofOfPurchaseUrl: "/mock/ticket-xiaomi.jpg",
    warrantyEndDate: new Date("2026-04-01"),
    serialLast4: "5847",
    photos: [
      "https://images.unsplash.com/photo-1571188654248-7a89213915f7?w=800",
    ],
    accessories: { "Cargador": true, "Llaves Allen": true, "Reflectores": true },
    estimatedValue: 580,
    estimatedValueUpdatedAt: new Date(),
    resaleValue: {
      percentage: 73,
      minPrice: 520,
      maxPrice: 620,
      marketTrend: "stable",
    },
    createdAt: new Date("2024-04-02"),
    updatedAt: new Date(),
  },
];

// ==========================================
// LISTINGS (Marketplace)
// ==========================================

export const mockListings: Listing[] = [
  {
    id: "list-1",
    productId: undefined,
    sellerId: "seller-1",
    seller: mockSellers[0], // Carlos García - Madrid
    categoryId: "cat-smartphones",
    category: mockCategories[0],
    title: "iPhone 14 Pro Max 256GB - Impecable",
    description: "Vendido por actualización. Siempre con funda y protector de pantalla. Sin ningún rasguño. Batería al 94%. Incluye cargador original y caja.",
    price: 899,
    location: "Madrid",
    shippingEnabled: true,
    shippingCost: 5.99,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: [
      "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=800",
      "https://images.unsplash.com/photo-1591337676887-a217a6970a8a?w=800",
    ],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    viewCount: 234,
    favoriteCount: 18,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-2",
    sellerId: "seller-2",
    seller: mockSellers[1], // Laura Martínez - Barcelona
    categoryId: "cat-laptops",
    category: mockCategories[2],
    title: "MacBook Air M2 13\" 512GB - Midnight",
    description: "Comprado hace 8 meses para teletrabajo pero apenas lo he usado. Menos de 50 ciclos de batería. Incluye cargador MagSafe y caja original.",
    price: 1149,
    location: "Barcelona",
    shippingEnabled: true,
    shippingCost: 8.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800",
    ],
    isBoosted: false,
    viewCount: 156,
    favoriteCount: 12,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-3",
    sellerId: "seller-3",
    seller: mockSellers[2], // Miguel Rodríguez - Valencia
    categoryId: "cat-consoles",
    category: mockCategories[3],
    title: "Nintendo Switch OLED + 3 juegos",
    description: "Nintendo Switch modelo OLED en blanco. Incluye base, Joy-Cons y 3 juegos: Zelda TOTK, Mario Kart 8 y Animal Crossing. Todo en perfecto estado.",
    price: 320,
    location: "Valencia",
    shippingEnabled: true,
    shippingCost: 6.99,
    verificationLevel: "LEVEL_0",
    hasVerifiedPurchase: false,
    hasValidWarranty: false,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: [
      "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800",
    ],
    isBoosted: false,
    viewCount: 89,
    favoriteCount: 7,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-4",
    sellerId: "seller-4",
    seller: mockSellers[3], // Ana López - Sevilla
    categoryId: "cat-audio",
    category: mockCategories[4],
    title: "Sony WH-1000XM5 - Negros",
    description: "Los mejores auriculares con cancelación de ruido. Comprados hace 6 meses, usados solo para viajes. Incluyen estuche, cable y cargador.",
    price: 275,
    location: "Sevilla",
    shippingEnabled: true,
    shippingCost: 4.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: [
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800",
    ],
    isBoosted: false,
    viewCount: 112,
    favoriteCount: 9,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-5",
    sellerId: "seller-5",
    seller: mockSellers[4], // Pablo Fernández - Bilbao
    categoryId: "cat-wearables",
    category: mockCategories[5],
    title: "Apple Watch Series 9 45mm GPS",
    description: "Apple Watch Series 9 en color Midnight. Batería al 100%. Incluye correa deportiva original y cargador magnético.",
    price: 369,
    location: "Bilbao",
    shippingEnabled: true,
    shippingCost: 4.99,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: [
      "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=800",
    ],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    viewCount: 178,
    favoriteCount: 15,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-6",
    sellerId: "seller-6",
    seller: mockSellers[5], // Elena Sánchez - Málaga
    categoryId: "cat-smartphones",
    category: mockCategories[0],
    title: "Samsung Galaxy S24 Ultra 512GB",
    description: "Samsung Galaxy S24 Ultra en Titanium Gray. Incluye S Pen, cargador 45W y funda original Samsung. Sin marcas de uso.",
    price: 1099,
    location: "Málaga",
    shippingEnabled: true,
    shippingCost: 5.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: [
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800",
    ],
    isBoosted: false,
    viewCount: 201,
    favoriteCount: 22,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  // === MÁS PRODUCTOS DE TECNOLOGÍA ===
  {
    id: "list-7",
    sellerId: "seller-7",
    seller: mockSellers[6], // Javier Ruiz - Zaragoza
    categoryId: "cat-laptops",
    title: "MacBook Pro 14\" M3 Pro 512GB",
    description: "MacBook Pro 14 pulgadas con chip M3 Pro. Comprado en diciembre 2024. Apenas 30 ciclos de batería. Incluye cargador 96W y caja original.",
    price: 1899,
    location: "Madrid",
    shippingEnabled: true,
    shippingCost: 9.99,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800"],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    viewCount: 312,
    favoriteCount: 28,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-8",
    sellerId: "seller-8",
    seller: mockSellers[7], // María Torres - Alicante
    categoryId: "cat-tablets",
    title: "iPad Pro 11\" M2 256GB WiFi+Cellular",
    description: "iPad Pro 11 pulgadas con chip M2. Perfecto estado. Incluye Magic Keyboard y Apple Pencil 2ª gen. Todo original.",
    price: 1050,
    location: "Barcelona",
    shippingEnabled: true,
    shippingCost: 7.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800"],
    isBoosted: false,
    viewCount: 145,
    favoriteCount: 11,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-9",
    sellerId: "seller-9",
    seller: mockSellers[8], // Daniel Jiménez - Granada
    categoryId: "cat-consoles",
    title: "PlayStation 5 Slim + 2 mandos",
    description: "PS5 Slim edición digital. Incluye 2 mandos DualSense (blanco y negro), base de carga y 5 juegos digitales.",
    price: 450,
    location: "Valencia",
    shippingEnabled: true,
    shippingCost: 8.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800"],
    isBoosted: false,
    viewCount: 198,
    favoriteCount: 16,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-10",
    sellerId: "seller-10",
    seller: mockSellers[9], // Sofía Moreno - Murcia
    categoryId: "cat-consoles",
    title: "Xbox Series X 1TB + Game Pass",
    description: "Xbox Series X en perfecto estado. Incluye mando Elite Series 2, soporte vertical y 8 meses de Game Pass Ultimate transferible.",
    price: 420,
    location: "Zaragoza",
    shippingEnabled: true,
    shippingCost: 8.99,
    verificationLevel: "LEVEL_0",
    hasVerifiedPurchase: false,
    hasValidWarranty: false,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800"],
    isBoosted: false,
    viewCount: 87,
    favoriteCount: 5,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
  },
  // === AUDIO ===
  {
    id: "list-11",
    sellerId: "seller-11",
    seller: mockSellers[10], // Alejandro Navarro - Valladolid
    categoryId: "cat-audio",
    title: "AirPods Pro 2 USB-C - Como nuevos",
    description: "AirPods Pro 2ª generación con USB-C. Comprados hace 3 meses. Batería al 100%. Incluyen todas las almohadillas y caja.",
    price: 199,
    location: "Sevilla",
    shippingEnabled: true,
    shippingCost: 3.99,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800"],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    viewCount: 256,
    favoriteCount: 19,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-12",
    sellerId: "seller-12",
    seller: mockSellers[11], // Carmen Vega - A Coruña
    categoryId: "cat-audio",
    title: "Bose QuietComfort Ultra Headphones",
    description: "Auriculares Bose QC Ultra en negro. Los mejores para cancelación de ruido. Incluyen estuche premium y cable de carga.",
    price: 320,
    location: "Bilbao",
    shippingEnabled: true,
    shippingCost: 4.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800"],
    isBoosted: false,
    viewCount: 134,
    favoriteCount: 8,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-13",
    sellerId: "seller-1",
    seller: mockSellers[0],
    categoryId: "cat-audio",
    title: "Sonos Era 300 - Altavoz premium",
    description: "Altavoz Sonos Era 300 con Dolby Atmos. Sonido espacial increíble. Usado solo 2 meses. Incluye caja y cable original.",
    price: 380,
    location: "Madrid",
    shippingEnabled: true,
    shippingCost: 6.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800"],
    isBoosted: false,
    viewCount: 76,
    favoriteCount: 4,
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
  },
  // === CÁMARAS ===
  {
    id: "list-14",
    sellerId: "seller-9",
    seller: mockSellers[8],
    categoryId: "cat-cameras",
    title: "Sony A7 IV + Lente 24-70mm f/2.8",
    description: "Cámara Sony A7 IV con lente Sony GM 24-70mm f/2.8. Solo 8.000 disparos. Incluye batería extra, cargador y mochila Lowepro.",
    price: 2800,
    location: "Barcelona",
    shippingEnabled: true,
    shippingCost: 14.99,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800"],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    viewCount: 423,
    favoriteCount: 35,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-15",
    sellerId: "seller-3",
    seller: mockSellers[2],
    categoryId: "cat-cameras",
    title: "Canon EOS R6 Mark II - Body",
    description: "Canon R6 Mark II solo cuerpo. 15.000 disparos. Estado impecable. Incluye batería extra y grip original Canon.",
    price: 1950,
    location: "Valencia",
    shippingEnabled: true,
    shippingCost: 12.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: false,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800"],
    isBoosted: false,
    viewCount: 187,
    favoriteCount: 14,
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-16",
    sellerId: "seller-6",
    seller: mockSellers[5],
    categoryId: "cat-cameras",
    title: "DJI Osmo Pocket 3 Creator Combo",
    description: "DJI Pocket 3 versión Creator Combo. Incluye módulo inalámbrico, micrófono DJI Mic, estuche de carga y todos los accesorios.",
    price: 480,
    location: "Málaga",
    shippingEnabled: true,
    shippingCost: 5.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800"],
    isBoosted: false,
    viewCount: 98,
    favoriteCount: 7,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  // === ELECTRODOMÉSTICOS ===
  {
    id: "list-17",
    sellerId: "seller-1",
    seller: mockSellers[0],
    categoryId: "cat-appliances-small",
    title: "Dyson V15 Detect Absolute",
    description: "Aspirador Dyson V15 con láser detector de polvo. Todos los accesorios incluidos. Batería al 95%. Factura de El Corte Inglés.",
    price: 480,
    location: "Madrid",
    shippingEnabled: true,
    shippingCost: 9.99,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800"],
    isBoosted: false,
    viewCount: 234,
    favoriteCount: 18,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-18",
    sellerId: "seller-4",
    seller: mockSellers[3],
    categoryId: "cat-appliances-small",
    title: "Thermomix TM6 + Cookidoo 1 año",
    description: "Thermomix TM6 en perfecto estado. Poco uso. Incluye vaso extra, mariposa extra y suscripción Cookidoo transferible por 1 año.",
    price: 1100,
    location: "Sevilla",
    shippingEnabled: true,
    shippingCost: 14.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1585515320310-259814833e62?w=800"],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    viewCount: 567,
    favoriteCount: 42,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-19",
    sellerId: "seller-2",
    seller: mockSellers[1],
    categoryId: "cat-appliances-small",
    title: "iRobot Roomba j9+ Combo",
    description: "Robot Roomba j9+ que aspira y friega. Base de autovaciado incluida. Solo 3 meses de uso. Garantía hasta 2026.",
    price: 750,
    location: "Barcelona",
    shippingEnabled: true,
    shippingCost: 11.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1667685314566-dbe4fbc51134?w=800"],
    isBoosted: false,
    viewCount: 189,
    favoriteCount: 15,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  // === BEBÉS Y NIÑOS ===
  {
    id: "list-20",
    sellerId: "seller-1",
    seller: mockSellers[0],
    categoryId: "cat-baby-strollers",
    title: "Bugaboo Fox 5 - Negro/Grafito",
    description: "Cochecito Bugaboo Fox 5 completo. Incluye capazo, silla, barra delantera y saco de invierno. Usado 8 meses. Impecable.",
    price: 850,
    location: "Madrid",
    shippingEnabled: true,
    shippingCost: 19.99,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800"],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    viewCount: 345,
    favoriteCount: 28,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-21",
    sellerId: "seller-8",
    seller: mockSellers[7],
    categoryId: "cat-baby-strollers",
    title: "Babyzen YOYO2 6+ Negro",
    description: "Silla de paseo Babyzen YOYO2 para mayores de 6 meses. La más compacta del mercado. Incluye bolsa de transporte y adaptadores Maxi-Cosi.",
    price: 380,
    location: "Barcelona",
    shippingEnabled: true,
    shippingCost: 12.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: false,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800"],
    isBoosted: false,
    viewCount: 234,
    favoriteCount: 19,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-22",
    sellerId: "seller-3",
    seller: mockSellers[2],
    categoryId: "cat-baby-car-seats",
    title: "Cybex Sirona Z i-Size + Base Z",
    description: "Silla de coche Cybex Sirona Z giratoria con base Isofix. Usada 1 año. Sin accidentes. Incluye protector de asiento.",
    price: 320,
    location: "Valencia",
    shippingEnabled: true,
    shippingCost: 14.99,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: false,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1544476915-ed1370594142?w=800"],
    isBoosted: false,
    viewCount: 156,
    favoriteCount: 12,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  // === DEPORTE Y FITNESS ===
  {
    id: "list-23",
    sellerId: "seller-1",
    seller: mockSellers[0],
    categoryId: "cat-fitness",
    title: "Peloton Bike+ con pantalla giratoria",
    description: "Bicicleta Peloton Bike+ con pantalla de 24\" giratoria. Incluye zapatillas Peloton talla 43, pesas y esterilla. Suscripción no incluida.",
    price: 1600,
    location: "Madrid",
    shippingEnabled: false,
    shippingCost: 0,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1591291621164-2c6367723315?w=800"],
    isBoosted: false,
    viewCount: 287,
    favoriteCount: 21,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-24",
    sellerId: "seller-5",
    seller: mockSellers[4],
    categoryId: "cat-bikes",
    title: "Specialized Turbo Levo SL Comp",
    description: "E-MTB Specialized Turbo Levo SL talla L. Motor SL 1.1. Ruedas 29\". Solo 800km. Incluye cargador y manual.",
    price: 4200,
    location: "Bilbao",
    shippingEnabled: true,
    shippingCost: 49.99,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800"],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    viewCount: 456,
    favoriteCount: 38,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-25",
    sellerId: "seller-2",
    seller: mockSellers[1],
    categoryId: "cat-ebikes",
    title: "VanMoof S5 - Bici urbana eléctrica",
    description: "VanMoof S5 en gris oscuro. 500km. Batería perfecta. Incluye candado integrado, luces y app transferible.",
    price: 1800,
    location: "Barcelona",
    shippingEnabled: true,
    shippingCost: 39.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1571188654248-7a89213915f7?w=800"],
    isBoosted: false,
    viewCount: 312,
    favoriteCount: 25,
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
  },
  // === MODA Y LUJO ===
  {
    id: "list-26",
    sellerId: "seller-12",
    seller: mockSellers[11],
    categoryId: "cat-watches-jewelry",
    title: "Rolex Submariner Date 126610LN",
    description: "Rolex Submariner Date 41mm. Comprado en joyería oficial 2023. Set completo: caja, papeles, garantía. Sin uso.",
    price: 12500,
    location: "Madrid",
    shippingEnabled: true,
    shippingCost: 0,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800"],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    viewCount: 1234,
    favoriteCount: 89,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-27",
    sellerId: "seller-2",
    seller: mockSellers[1],
    categoryId: "cat-watches-jewelry",
    title: "Omega Speedmaster Moonwatch",
    description: "Omega Speedmaster Professional Moonwatch 42mm. Movimiento manual. Set completo con estuche NASA y documentación.",
    price: 5800,
    location: "Barcelona",
    shippingEnabled: true,
    shippingCost: 0,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800"],
    isBoosted: false,
    viewCount: 678,
    favoriteCount: 52,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-28",
    sellerId: "seller-12",
    seller: mockSellers[11],
    categoryId: "cat-fashion-luxury",
    title: "Louis Vuitton Neverfull MM Damier",
    description: "Bolso LV Neverfull MM en Damier Ebene. Comprado en tienda oficial. Incluye pochette interior, dust bag y bolsa original.",
    price: 1200,
    location: "Madrid",
    shippingEnabled: true,
    shippingCost: 0,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: false,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800"],
    isBoosted: false,
    viewCount: 456,
    favoriteCount: 34,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  // === INSTRUMENTOS MUSICALES ===
  {
    id: "list-29",
    sellerId: "seller-4",
    seller: mockSellers[3],
    categoryId: "cat-instruments",
    title: "Fender Stratocaster American Pro II",
    description: "Fender Stratocaster American Professional II en Sunburst. Mástil de arce. Incluye estuche rígido Fender y certificado.",
    price: 1450,
    location: "Sevilla",
    shippingEnabled: true,
    shippingCost: 24.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1564186763535-ebb21ef5277f?w=800"],
    isBoosted: false,
    viewCount: 234,
    favoriteCount: 18,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-30",
    sellerId: "seller-3",
    seller: mockSellers[2],
    categoryId: "cat-instruments",
    title: "Roland TD-17KVX E-Drum Kit",
    description: "Batería electrónica Roland TD-17KVX completa. Incluye pedal doble, banqueta, auriculares y baquetas. Perfecta para practicar en casa.",
    price: 1200,
    location: "Valencia",
    shippingEnabled: true,
    shippingCost: 29.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=800"],
    isBoosted: false,
    viewCount: 167,
    favoriteCount: 12,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
  },
  // === DRONES ===
  {
    id: "list-31",
    sellerId: "seller-6",
    seller: mockSellers[5],
    categoryId: "cat-drones",
    title: "DJI Mavic 3 Pro Fly More Combo",
    description: "DJI Mavic 3 Pro con cámara Hasselblad. Combo con 3 baterías, hub de carga, filtros ND y mochila DJI. Menos de 20 vuelos.",
    price: 1900,
    location: "Málaga",
    shippingEnabled: true,
    shippingCost: 12.99,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800"],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
    viewCount: 389,
    favoriteCount: 31,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-32",
    sellerId: "seller-5",
    seller: mockSellers[4],
    categoryId: "cat-drones",
    title: "DJI Mini 4 Pro + DJI RC 2",
    description: "DJI Mini 4 Pro con mando RC 2 con pantalla. Peso <249g (sin licencia). Incluye 3 baterías y estuche de carga.",
    price: 850,
    location: "Bilbao",
    shippingEnabled: true,
    shippingCost: 8.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?w=800"],
    isBoosted: false,
    viewCount: 245,
    favoriteCount: 19,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  // === HERRAMIENTAS ===
  {
    id: "list-33",
    sellerId: "seller-7",
    seller: mockSellers[6],
    categoryId: "cat-power-tools",
    title: "Makita Kit 18V LXT 6 herramientas",
    description: "Kit profesional Makita 18V con taladro, atornillador de impacto, sierra circular, lijadora, linterna y aspirador. 4 baterías 5Ah.",
    price: 850,
    location: "Zaragoza",
    shippingEnabled: true,
    shippingCost: 14.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800"],
    isBoosted: false,
    viewCount: 178,
    favoriteCount: 14,
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
  },
  // === TV ===
  {
    id: "list-34",
    sellerId: "seller-1",
    seller: mockSellers[0],
    categoryId: "cat-tv",
    title: "LG OLED C3 65\" + Barra Sonido",
    description: "TV LG OLED evo C3 de 65 pulgadas. Incluye barra de sonido LG S95QR con Dolby Atmos. Ambos con garantía hasta 2026.",
    price: 1800,
    location: "Madrid",
    shippingEnabled: false,
    shippingCost: 0,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800"],
    isBoosted: false,
    viewCount: 312,
    favoriteCount: 24,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-35",
    sellerId: "seller-2",
    seller: mockSellers[1],
    categoryId: "cat-tv",
    title: "Samsung QN85C Neo QLED 55\"",
    description: "TV Samsung Neo QLED 4K de 55 pulgadas. Gaming Hub integrado. Solo 6 meses de uso. Factura y garantía.",
    price: 850,
    location: "Barcelona",
    shippingEnabled: false,
    shippingCost: 0,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1558888401-3cc1de77652d?w=800"],
    isBoosted: false,
    viewCount: 198,
    favoriteCount: 15,
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
  },
  // === GAMING ACCESORIOS ===
  {
    id: "list-36",
    sellerId: "seller-3",
    seller: mockSellers[2],
    categoryId: "cat-gaming",
    title: "Razer Huntsman V3 Pro + DeathAdder",
    description: "Teclado Razer Huntsman V3 Pro con switches ópticos + ratón DeathAdder V3 Pro. Ambos en negro. Usados 4 meses.",
    price: 320,
    location: "Valencia",
    shippingEnabled: true,
    shippingCost: 6.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800"],
    isBoosted: false,
    viewCount: 145,
    favoriteCount: 11,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-37",
    sellerId: "seller-4",
    seller: mockSellers[3],
    categoryId: "cat-gaming",
    title: "Steam Deck OLED 1TB",
    description: "Steam Deck OLED versión de 1TB. Comprada en diciembre. Incluye dock oficial, funda y cristal templado instalado.",
    price: 580,
    location: "Sevilla",
    shippingEnabled: true,
    shippingCost: 7.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1640955014216-75201056c829?w=800"],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    viewCount: 423,
    favoriteCount: 35,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  // === SMARTPHONES ADICIONALES ===
  {
    id: "list-38",
    sellerId: "seller-5",
    seller: mockSellers[4],
    categoryId: "cat-smartphones",
    title: "Google Pixel 8 Pro 256GB",
    description: "Pixel 8 Pro en Bay (azul). 7 meses de uso. Batería al 97%. Incluye cargador 30W, funda Google y protector.",
    price: 750,
    location: "Bilbao",
    shippingEnabled: true,
    shippingCost: 5.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800"],
    isBoosted: false,
    viewCount: 187,
    favoriteCount: 14,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-39",
    sellerId: "seller-1",
    seller: mockSellers[0],
    categoryId: "cat-smartphones",
    title: "iPhone 15 Pro 256GB Titanio Natural",
    description: "iPhone 15 Pro en Titanio Natural. AppleCare+ hasta 2026. Sin ningún rasguño. Batería al 100%.",
    price: 1050,
    location: "Madrid",
    shippingEnabled: true,
    shippingCost: 5.99,
    verificationLevel: "LEVEL_2",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: true,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800"],
    isBoosted: true,
    boostedUntil: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
    viewCount: 567,
    favoriteCount: 45,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "list-40",
    sellerId: "seller-7",
    seller: mockSellers[6],
    categoryId: "cat-smartphones",
    title: "OnePlus 12 16GB/512GB",
    description: "OnePlus 12 versión tope de gama. Cámara Hasselblad. Carga 100W incluida. Solo 2 meses de uso.",
    price: 780,
    location: "Zaragoza",
    shippingEnabled: true,
    shippingCost: 5.99,
    verificationLevel: "LEVEL_1",
    hasVerifiedPurchase: true,
    hasValidWarranty: true,
    hasVerifiedAccessories: true,
    hasVerifiedIdentifier: false,
    status: "PUBLISHED",
    photos: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800"],
    isBoosted: false,
    viewCount: 134,
    favoriteCount: 9,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
];

// ==========================================
// CONVERSATIONS & MESSAGES
// ==========================================

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    listingId: "list-1",
    listing: mockListings[0],
    buyerId: "user-1",
    sellerId: "user-2",
    currentOffer: 850,
    offerStatus: "pending",
    messages: [
      {
        id: "msg-1",
        conversationId: "conv-1",
        senderId: "user-1",
        text: "Hola! Sigue disponible el iPhone?",
        isOffer: false,
        isSystemMessage: false,
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
      {
        id: "msg-2",
        conversationId: "conv-1",
        senderId: "user-2",
        text: "Hola! Sí, todavía lo tengo disponible.",
        isOffer: false,
        isSystemMessage: false,
        createdAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000),
      },
      {
        id: "msg-3",
        conversationId: "conv-1",
        senderId: "user-1",
        text: "Te ofrezco 850€",
        isOffer: true,
        offerAmount: 850,
        isSystemMessage: false,
        createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
];

// ==========================================
// ORDERS
// ==========================================

export const mockOrders: Order[] = [
  {
    id: "order-1",
    listingId: "list-old-1",
    buyerId: "user-1",
    sellerId: "seller-7",
    seller: mockSellers[6], // Javier Ruiz - Zaragoza
    amount: 650,
    shippingAmount: 5.99,
    feeMarketplace: 45.5,
    feeProtection: 13,
    total: 714.49,
    sellerPayout: 604.5,
    status: "ACCEPTED",
    trackingNumber: "MRW123456789",
    carrier: "MRW",
    isLocalPickup: false,
    paidAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    shippedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    deliveredAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    acceptedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    releasedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
];

// ==========================================
// ALERTS
// ==========================================

export const mockAlerts: Alert[] = [
  {
    id: "alert-1",
    userId: "user-1",
    productId: "prod-1",
    type: "sell_now",
    title: "Buen momento para vender",
    message: "Tu iPhone 15 Pro mantiene buen valor. Ahora puedes obtener 1.050€",
    isRead: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "alert-2",
    userId: "user-1",
    productId: "prod-3",
    type: "warranty_expiring",
    title: "Garantía próxima a expirar",
    message: "La garantía de tu PlayStation 5 expira en 60 días",
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "alert-3",
    userId: "user-1",
    productId: "prod-2",
    type: "price_drop",
    title: "Bajada de precio detectada",
    message: "Los AirPods Pro han bajado un 8% este mes en el mercado",
    isRead: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
];

// ==========================================
// HELPER FUNCTIONS
// ==========================================

export function getProductById(id: string): Product | undefined {
  return mockProducts.find((p) => p.id === id);
}

export function getListingById(id: string): Listing | undefined {
  return mockListings.find((l) => l.id === id);
}

// Get listings by seller ID
export function getListingsBySellerId(sellerId: string): Listing[] {
  return mockListings.filter((l) => l.sellerId === sellerId);
}

// Get active listings by seller ID (published)
export function getActiveListingsBySellerId(sellerId: string): Listing[] {
  return mockListings.filter((l) => l.sellerId === sellerId && l.status === "PUBLISHED");
}

// Get sold listings by seller ID
export function getSoldListingsBySellerId(sellerId: string): Listing[] {
  return mockListings.filter((l) => l.sellerId === sellerId && l.status === "SOLD");
}

export function getCategoryById(id: string): Category | undefined {
  return mockCategories.find((c) => c.id === id);
}

export function getConversationById(id: string): Conversation | undefined {
  return mockConversations.find((c) => c.id === id);
}

// Calculate total wallet value
export function calculateWalletValue(products: Product[]): number {
  return products.reduce((total, product) => total + (product.estimatedValue || 0), 0);
}

// Get price recommendation based on estimated value
export function getPriceRecommendations(estimatedValue: number) {
  return {
    minimo: Math.round(estimatedValue * 0.80), // El más bajo (venta instantánea)
    rapido: Math.round(estimatedValue * 0.90), // 90% del ideal (sin malvender)
    ideal: Math.round(estimatedValue),         // El precio justo del mercado
  };
}
